### ISSUE TITLE
Disable CardFlip animation for first item.

### ISSUE THREAD

**Issue by fantasticrahulrai** [wajahatkarim3/EasyFlipViewPager#10]
if we try to access the 2nd (or nth) fragment of the view pager 2 then also it gives the flip animation. Which sometimes results in delayed UI. Please let us know if there's a way to fix this, or any code snippets that should be added to the original library.

**Comment by wajahatkarim3** [comment]
You mean programmatically accessing nth fragment page? If that's the case, then you might be using this code to do that.
```
viewpager.setCurrentItem(4)
```
The `setCurrentItem(int item, boolean smoothScroll)` comes with two params: the page index and whether it should animate or not. If you call this method with `smoothScroll` as false, then you won't see the delay like this:

```
viewpager2.setCurrentItem(4, false)
```

Let me know if this helps.

**Comment by fantasticrahulrai** [comment]
Wow, thanks a lot dear, that's what I was looking for. Saved a lot of my time.

**Comment by wajahatkarim3** [comment]
No problem. Happy to help
